# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.SmallIntegerField(default=1),
        ),
    ]
