# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.SmallIntegerField(default=0),
        ),
    ]
